### PR TITLE
feat: support generating gitlab hosted plugins

### PR DESCRIPTION
**Pull request by hickey**
@jthegedus I had a few mins and found the asdf-plugin-template repo. Here are a few thoughts on some adaptations to integrate into GitLab better.

### CODE REVIEW

**Comment by jthegedus** [comment]
@hickey Thanks for adding these, are you able to further integrate this with the `setup.bash` script? That is, a question to the user about GitHub vs GitLab and then only output the correct files/delete the unused files?

**Comment by hickey** [comment]
I did look briefly at the script to just see what it was doing. I have not tried to modify the script as I did not want to make too many changes and introduce any issues that need to be fixed later on. I would certainly be happy to dig into the script more and start looking at what it would take to support both GitHub and GitLab.

**Comment by hickey** [comment]
I should have added, I will cut a new branch and create a new PR for changes to `setup.bash`.

**Comment by hickey** [comment]
I have rebased against the current `master` and have now added support for GitLab repos to the `setup.bash` script. 

For the `template/README.md` and `template/contributing.md` files, I found it more convenient to split them into 2 versions (one for GitHub and one for GitLab) and then just move the correct one in to place when cutting the final branch. 

I have also updated this to use current branch rather than just `master`. This will aid if the repo is moved to another repo where the default branch name is `main` or where someone forks the repo and prefers to use a branch name other than `master`.

**Comment by hickey** [comment]
I am a bit confused..... 

The two tests above that failed show a log from a commit which I can not find in the original or my forked repo. That commit is showing an old user email that predates anything I have done on any `asdf` work. Not sure where it is coming from or how it is being seen.

**Comment by hickey** [comment]
OK. I have figured out the issue with the old email address. Now I remember the cluster that I had to work around.....

My old mail server kept rejecting emails from GitHub and the only way I could receive notifications was to use the previous job's email address. I have just been able to verify my personal email address (thank you new mail server!) and have deleted the now defunct address. Everything will point to the correct email address now. 

Maybe if you rerun the workflows the checks will be successful now? At least I hope so.

**Comment by jthegedus** [comment]
I'll review this PR and resolve any test issues, thanks for your changes.

**Comment by jthegedus** [comment]
@hickey I have merged and will hotfix the issues

**Comment by jthegedus** [comment]
So the issue is with `primary_branch="$(git rev-parse --abbrev-ref HEAD)"`

Sometimes it resolves to `master` correctly in CI, but then doesn't clean up the `template/` dir. Other times it resolves to `HEAD` and then git fails but the script continues and `template/` remains.

**Comment by jthegedus** [comment]
@hickey I reverted the `git rev-parse` as I couldn't get a working solution. If you wish to tackle this issue again, please try from the latest code. (I left `primary_branch` code so it will be easy to experiment with)

**Comment by jthegedus** [comment]
The default is now `main`.

**Comment by hickey** [comment]
I think that some of the problem (at least from what I can see from the logs) is that the tests are occurring on a detatched head before the code is fully merged into the target branch. I suspect that is why at times it is showing up as `HEAD`. Then when `setup.bash` comes back around to check out the modified `master`/`main` branch if fails because `$primary_branch` is set to `HEAD` instead of the name of the branch. ARG... trying to be too clever. 

I will need to think about this for a bit to see if I can think up a way to detect the primary branch without being affected by a detached head scenario. I think I will be able to simulate this by trying to merge using the SHA1 hash values which should by default put me on a detached head (in theory).

**Pull request merged**
